ifneq ($(CONFIG_OF),)
obj-y					+= clk.o dpll.o autoidle.o gate.o \
					   clockdomain.o apll.o clk-44xx.o \
					   clk-54xx.o clk-7xx.o clk-33xx.o \
					   clk-43xx.o interface.o clk-3xxx.o
obj-$(CONFIG_SOC_DRA7XX)		+= clk-dra7-atl.o

endif
