#
# Makefile for the phy drivers.
#

obj-$(CONFIG_GENERIC_PHY)	+= phy-core.o
obj-$(CONFIG_OMAP_CONTROL_PHY)	+= phy-omap-control.o
obj-$(CONFIG_OMAP_USB2)		+= phy-omap-usb2.o
obj-$(CONFIG_OMAP_PIPE3)	+= phy-omap-pipe3.o
obj-$(CONFIG_TWL4030_USB)	+= phy-twl4030-usb.o
