# SPDX-License-Identifier: GPL-2.0
#
# Make file to build device tree binaries for boards based on
# Texas Instruments Inc processors
#
# Copyright (C) 2016-2017 Texas Instruments Incorporated - http://www.ti.com/
#
dtb-$(CONFIG_ARCH_K3_AM6) += k3-am654-vlab.dtb
dtb-$(CONFIG_ARCH_K3_AM6) += k3-am654-qt.dtb
dtb-$(CONFIG_ARCH_K3_AM6) += k3-am654-zebu.dtb

dtb-$(CONFIG_ARCH_K3_J7) += k3-j7-vlab.dtb
